version: '3.5'

services:
  word-cloud:
    container_name: word-cloud
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
